name: "Build, Push and Deploy API to ECS"

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Dispara o pipeline em tags como v1.0.0, v1.2.3, etc.

env:
  ENVIRONMENT: "dev"
  AWS_REGION: "sa-east-1"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Define ECR repository and image tag
        id: ecr-meta
        run: |
          ECR_REPOSITORY="ecr-repo-${{ env.ENVIRONMENT }}"
          IMAGE_TAG="${{ github.ref_name }}"
          echo "ECR_REPOSITORY=${ECR_REPOSITORY}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} -f ./api/Dockerfile ./api
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          echo "image=$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition "api-task-${{ env.ENVIRONMENT }}" --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: render-task-definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: "api-container" # Nome do container na sua task definition
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-definition.outputs.task-definition }}
          service: "service-api-${{ env.ENVIRONMENT }}"
          cluster: "cluster-desafio-${{ env.ENVIRONMENT }}"
          wait-for-service-stability: true # Mantém a espera para garantir o deploy